# Generated by Django 3.0.3 on 2020-03-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200329_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
